services:
  pichub:
    image: ghcr.nju.edu.cn/untitled572/pichub-aggregator:latest
    network_mode: host
    volumes:
      - ./pichub_data:/app/data
      - ./pichub_cache:/app/cache
      - ./pichub_saved:/app/data/saved
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=5721
      - DB_PATH=/app/data/pichub.db
      - CACHE_PATH=/app/cache
      - TRUSTED_PROXIES=127.0.0.1/32
    restart: unless-stopped
